name: Dev Workflow
run-name: Dev by ${{ github.actor }}

on:
  [push]
  # push:
    # branches:
      # - dev

jobs:
  Explore-Dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ› ï¸ DEV Workflow triggered by ${{ github.event_name }}."
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "ğŸ§ª Running on branch: ${{ github.ref }}"
      - run: echo "ğŸ“‚ Files in workspace:"
      - run: ls ${{ github.workspace }}
      - run: echo "âœ… Dev workflow completed successfully!"
